apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: practica2inst2
  namespace: practica2inst2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-server
        image: nginx
