apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvolume-pvc
  namespace: backend
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
