apiVersion: v1
kind: PersistentVolume
metadata:
  name: practica-final-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /work
