apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: contentserver-rplst
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contentserver
      tier: frontend
  template:
    metadata:
      labels:
        app: contentserver
        tier: frontend
        app.kubernetes.io/name: contentserverApp
    spec:
      containers:
      - name: contentserver
        image: jlaredo/formacion-static-server-amd64
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - front
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - contentserver
            topologyKey: "kubernetes.io/hostname"
