apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rplst
  namespace: frontend
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - name: webserver
        image:  jlaredo/formacion-web-server-amd64
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: webserver-cm
        - secretRef:
            name: bdsecret-sc
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - front
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webserver
            topologyKey: "kubernetes.io/hostname"
